/**
 * Locale-keyed labels for the generated report "chrome" (titles, section headings, KPI
 * labels, table column headers) — everything in `Report` that isn't a direct copy of tenant
 * data (risk titles, policy names, framework short names stay as stored/canonical, per
 * CLAUDE.md — internationally recognized framework names/codes are never translated).
 * Node-only; consumed by `lib/reports/service.ts`.
 */

import type { AppLocale } from "@/i18n/routing";
import type { RiskCategory, RiskStatus, Severity } from "@/lib/risk/types";
import type { PolicyStatus } from "@/lib/policies/types";
import type { PolicyRecommendationCategory } from "@/lib/policyRecommendations/types";
import type { PlanItemStatus } from "@/lib/planExecution/types";
import type { ReportKind } from "./types";

export interface ReportLabels {
  meta: Record<ReportKind, { title: string; subtitle: string }>;
  tenantPrefix: string;
  generatedByPrefix: string;
  kpis: {
    complianceCoverage: string;
    controlGaps: string;
    openRisks: string;
    criticalRisks: string;
    evidenceArtifacts: string;
    publishedPolicies: string;
    overallCoverage: string;
    controlsCovered: string;
    openGaps: string;
    policies: string;
    totalRisks: string;
    critical: string;
    high: string;
    accepted: string;
    averageScore: string;
  };
  sections: {
    frameworkCoverage: string;
    topRisks: string;
    controlGaps: string;
    policyRegister: string;
    severityDistribution: string;
    riskRegister: string;
    governanceStatus: string;
    policyStatus: string;
    documentReview: string;
    actionPlan: string;
    keyFindings: string;
    recommendations: string;
    nextSteps: string;
    references: string;
  };
  tables: {
    frameworkCoverageTitle: string;
    highestScoringRisks: string;
    controlsWithoutEvidence: string;
    policyRegisterTitle: string;
    risksBySeverity: string;
    allRisks: string;
    noControlGaps: string;
    policyStatusTitle: string;
    documentReviewTitle: string;
    actionPlanTitle: string;
    recommendationsTitle: string;
    referencesTitle: string;
  };
  columns: {
    framework: string;
    controls: string;
    covered: string;
    coverage: string;
    region: string;
    risk: string;
    category: string;
    score: string;
    severity: string;
    status: string;
    control: string;
    title: string;
    policy: string;
    owner: string;
    mappedControls: string;
    count: string;
    inherent: string;
    residual: string;
    task: string;
    priority: string;
    dueDate: string;
    document: string;
    uploadedDate: string;
    recommendation: string;
    reason: string;
    reference: string;
  };
  severity: Record<Severity, string>;
  riskStatus: Record<RiskStatus, string>;
  riskCategory: Record<RiskCategory, string>;
  policyStatusLabel: Record<PolicyStatus, string>;
  recommendationCategory: Record<PolicyRecommendationCategory, string>;
  planItemStatus: Record<PlanItemStatus, string>;
  noDueDate: string;
  governanceNotStarted: string;
  governanceActive: (version: number, done: number, total: number) => string;
  governanceReviewDue: string;
  governanceNextReview: (date: string) => string;
  noPolicies: string;
  noDocuments: string;
  documentsSummary: (total: number, processed: number) => string;
  noOpenActionItems: string;
  noKeyFindings: string;
  noRecommendations: string;
  nextStepsIntro: string;
  nextStepsNoneUrgent: string;
  nextStepsReviewDue: string;
  nextStepsCompleteAssessment: string;
}

const EN: ReportLabels = {
  meta: {
    executive: {
      title: "Executive GRC Report",
      subtitle: "Governance, risk & compliance posture at a glance",
    },
    compliance: {
      title: "Compliance Report",
      subtitle: "Framework coverage and control assurance",
    },
    risk: { title: "Risk Report", subtitle: "Risk register, scoring, and treatment" },
  },
  tenantPrefix: "Tenant",
  generatedByPrefix: "Generated by",
  kpis: {
    complianceCoverage: "Compliance coverage",
    controlGaps: "Control gaps",
    openRisks: "Open risks",
    criticalRisks: "Critical risks",
    evidenceArtifacts: "Evidence artifacts",
    publishedPolicies: "Published policies",
    overallCoverage: "Overall coverage",
    controlsCovered: "Controls covered",
    openGaps: "Open gaps",
    policies: "Policies",
    totalRisks: "Total risks",
    critical: "Critical",
    high: "High",
    accepted: "Accepted",
    averageScore: "Average score",
  },
  sections: {
    frameworkCoverage: "Framework coverage",
    topRisks: "Top risks by inherent score",
    controlGaps: "Control gaps",
    policyRegister: "Policies",
    severityDistribution: "Severity distribution",
    riskRegister: "Risk register",
    governanceStatus: "Governance status",
    policyStatus: "Policy status",
    documentReview: "Document review",
    actionPlan: "Tasks / action plan",
    keyFindings: "Key findings",
    recommendations: "Recommendations",
    nextSteps: "Next steps",
    references: "References / sources",
  },
  tables: {
    frameworkCoverageTitle: "Coverage by framework",
    highestScoringRisks: "Highest-scoring risks",
    controlsWithoutEvidence: "Controls without evidence",
    policyRegisterTitle: "Policy register",
    risksBySeverity: "Risks by severity",
    allRisks: "All risks",
    noControlGaps: "No control gaps — every catalogued control has linked evidence.",
    policyStatusTitle: "Policies by status",
    documentReviewTitle: "Uploaded documents",
    actionPlanTitle: "Open action items",
    recommendationsTitle: "Pending policy recommendations",
    referencesTitle: "Sources cited by recommendations",
  },
  columns: {
    framework: "Framework",
    controls: "Controls",
    covered: "Covered",
    coverage: "Coverage",
    region: "Region",
    risk: "Risk",
    category: "Category",
    score: "Score",
    severity: "Severity",
    status: "Status",
    control: "Control",
    title: "Title",
    policy: "Policy",
    owner: "Owner",
    mappedControls: "Mapped controls",
    count: "Count",
    inherent: "Inherent",
    residual: "Residual",
    task: "Task",
    priority: "Priority",
    dueDate: "Due date",
    document: "Document",
    uploadedDate: "Uploaded",
    recommendation: "Recommendation",
    reason: "Reason",
    reference: "Source",
  },
  severity: { low: "Low", medium: "Medium", high: "High", critical: "Critical" },
  riskStatus: { open: "Open", mitigating: "Mitigating", accepted: "Accepted", closed: "Closed" },
  riskCategory: {
    cyber: "Cyber",
    compliance: "Compliance",
    privacy: "Privacy",
    operational: "Operational",
    third_party: "Third party",
    financial: "Financial",
  },
  policyStatusLabel: {
    draft: "Draft",
    in_review: "In review",
    published: "Published",
    archived: "Archived",
  },
  recommendationCategory: {
    general: "General policies",
    sector: "Sector-specific policies",
    establishment: "Specific to this organization",
  },
  planItemStatus: {
    not_started: "Not started",
    in_progress: "In progress",
    done: "Done",
    deferred: "Deferred",
    not_applicable: "Not applicable",
  },
  noDueDate: "no due date",
  governanceNotStarted:
    "This organization has not completed a governance assessment yet — there is no active governance plan.",
  governanceActive: (version, done, total) =>
    `The governance plan (v${version}) is active. Of ${total} total action items, ${done} are complete and ${total - done} remain open.`,
  governanceReviewDue: "The periodic review of this plan is due now.",
  governanceNextReview: (date) => `Next review due ${date}.`,
  noPolicies: "No policies recorded for this organization yet.",
  noDocuments: "No documents have been uploaded for this organization yet.",
  documentsSummary: (total, processed) =>
    `${total} document(s) uploaded in total, ${processed} processed and retrievable by the AI Assistant.`,
  noOpenActionItems: "No open action items — every governance plan item is complete or not applicable.",
  noKeyFindings: "No key findings recorded from the current assessment.",
  noRecommendations: "No pending policy recommendations at this time.",
  nextStepsIntro: "Recommended priority next steps:",
  nextStepsNoneUrgent: "No urgent next steps — every governance plan item is complete.",
  nextStepsReviewDue: "The periodic governance plan review is also due now.",
  nextStepsCompleteAssessment:
    "The recommended next step is to complete the governance assessment to generate an action plan.",
};

const AR: ReportLabels = {
  meta: {
    executive: {
      title: "التقرير التنفيذي للحوكمة والمخاطر والامتثال",
      subtitle: "نظرة شاملة على وضع الحوكمة والمخاطر والامتثال",
    },
    compliance: {
      title: "تقرير الامتثال",
      subtitle: "تغطية الأطر التنظيمية وضمان الضوابط",
    },
    risk: { title: "تقرير المخاطر", subtitle: "سجل المخاطر والتقييم والمعالجة" },
  },
  tenantPrefix: "الجهة",
  generatedByPrefix: "أُعد بواسطة",
  kpis: {
    complianceCoverage: "تغطية الامتثال",
    controlGaps: "فجوات الضوابط",
    openRisks: "المخاطر المفتوحة",
    criticalRisks: "المخاطر الحرجة",
    evidenceArtifacts: "الأدلة الموثقة",
    publishedPolicies: "السياسات المعتمدة",
    overallCoverage: "التغطية الإجمالية",
    controlsCovered: "الضوابط المغطاة",
    openGaps: "الفجوات المفتوحة",
    policies: "السياسات",
    totalRisks: "إجمالي المخاطر",
    critical: "حرجة",
    high: "عالية",
    accepted: "مقبولة",
    averageScore: "متوسط الدرجة",
  },
  sections: {
    frameworkCoverage: "تغطية الأطر التنظيمية",
    topRisks: "أعلى المخاطر حسب درجة الخطورة الكامنة",
    controlGaps: "فجوات الضوابط",
    policyRegister: "السياسات",
    severityDistribution: "توزيع درجات الخطورة",
    riskRegister: "سجل المخاطر",
    governanceStatus: "حالة برنامج الحوكمة",
    policyStatus: "حالة السياسات",
    documentReview: "مراجعة المستندات",
    actionPlan: "المهام / خطة العمل",
    keyFindings: "النتائج الرئيسية",
    recommendations: "التوصيات",
    nextSteps: "الخطوات التالية",
    references: "المراجع / المصادر",
  },
  tables: {
    frameworkCoverageTitle: "التغطية حسب الإطار",
    highestScoringRisks: "أعلى المخاطر درجة",
    controlsWithoutEvidence: "الضوابط بدون أدلة",
    policyRegisterTitle: "سجل السياسات",
    risksBySeverity: "المخاطر حسب درجة الخطورة",
    allRisks: "جميع المخاطر",
    noControlGaps: "لا توجد فجوات في الضوابط — كل ضابط مُصنّف مرتبط بدليل.",
    policyStatusTitle: "السياسات حسب الحالة",
    documentReviewTitle: "المستندات المرفوعة",
    actionPlanTitle: "المهام المفتوحة",
    recommendationsTitle: "توصيات السياسات المعلّقة",
    referencesTitle: "المصادر التي استندت إليها التوصيات",
  },
  columns: {
    framework: "الإطار",
    controls: "الضوابط",
    covered: "المغطاة",
    coverage: "نسبة التغطية",
    region: "المنطقة",
    risk: "الخطر",
    category: "الفئة",
    score: "الدرجة",
    severity: "درجة الخطورة",
    status: "الحالة",
    control: "الضابط",
    title: "العنوان",
    policy: "السياسة",
    owner: "المالك",
    mappedControls: "الضوابط المرتبطة",
    count: "العدد",
    inherent: "الكامنة",
    residual: "المتبقية",
    task: "المهمة",
    priority: "الأولوية",
    dueDate: "تاريخ الاستحقاق",
    document: "المستند",
    uploadedDate: "تاريخ الرفع",
    recommendation: "التوصية",
    reason: "السبب",
    reference: "المصدر",
  },
  severity: { low: "منخفضة", medium: "متوسطة", high: "عالية", critical: "حرجة" },
  riskStatus: { open: "مفتوح", mitigating: "قيد التخفيف", accepted: "مقبول", closed: "مغلق" },
  riskCategory: {
    cyber: "سيبراني",
    compliance: "امتثال",
    privacy: "خصوصية",
    operational: "تشغيلي",
    third_party: "طرف ثالث",
    financial: "مالي",
  },
  policyStatusLabel: {
    draft: "مسودة",
    in_review: "قيد المراجعة",
    published: "معتمدة",
    archived: "مؤرشفة",
  },
  recommendationCategory: {
    general: "سياسات عامة",
    sector: "سياسات خاصة بالقطاع",
    establishment: "خاصة بهذه المنشأة",
  },
  planItemStatus: {
    not_started: "لم تبدأ",
    in_progress: "قيد التنفيذ",
    done: "مكتملة",
    deferred: "مؤجّلة",
    not_applicable: "غير قابلة للتطبيق",
  },
  noDueDate: "بدون موعد",
  governanceNotStarted:
    "لم تُكمل هذه المنشأة برنامج تقييم الحوكمة بعد — لا توجد خطة حوكمة نشطة حالياً.",
  governanceActive: (version, done, total) =>
    `خطة الحوكمة (الإصدار ${version}) نشطة حالياً. من إجمالي ${total} مهمة، أُنجزت ${done} ومتبقٍ ${total - done}.`,
  governanceReviewDue: "المراجعة الدورية لهذه الخطة مستحقة الآن.",
  governanceNextReview: (date) => `موعد المراجعة القادمة: ${date}.`,
  noPolicies: "لا توجد سياسات مسجلة لهذه المنشأة بعد.",
  noDocuments: "لم تُرفع أي مستندات لهذه المنشأة بعد.",
  documentsSummary: (total, processed) =>
    `${total} مستندًا مرفوعًا إجمالاً، منها ${processed} تمت معالجته وأصبح قابلاً للاسترجاع ضمن إجابات المساعد الذكي.`,
  noOpenActionItems: "لا توجد مهام مفتوحة حالياً — جميع بنود خطة الحوكمة منجزة أو غير قابلة للتطبيق.",
  noKeyFindings: "لا توجد نتائج رئيسية مسجلة من التقييم الحالي.",
  noRecommendations: "لا توجد توصيات سياسات معلّقة حالياً.",
  nextStepsIntro: "الخطوات التالية الموصى بها حسب الأولوية:",
  nextStepsNoneUrgent: "لا توجد خطوات تالية عاجلة — جميع بنود خطة الحوكمة منجزة.",
  nextStepsReviewDue: "كما أن المراجعة الدورية لخطة الحوكمة مستحقة الآن.",
  nextStepsCompleteAssessment: "الخطوة التالية الموصى بها هي إكمال برنامج تقييم الحوكمة لإنشاء خطة عمل.",
};

export function getReportLabels(locale: AppLocale): ReportLabels {
  return locale === "ar" ? AR : EN;
}
