/**
 * PDF report renderer using pdf-lib (no external service). Produces an audit-ready A4
 * document with a title block, headline KPIs, and section tables that paginate. Node-only.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import { formatReportTimestamp } from "./format";
import type { Report, ReportTable } from "./types";

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

const INK = rgb(0.09, 0.09, 0.11);
const BODY = rgb(0.2, 0.2, 0.24);
const MUTED = rgb(0.45, 0.45, 0.5);
const ACCENT = rgb(0.43, 0.42, 0.87);
const LINE = rgb(0.85, 0.85, 0.88);
const HEADER_BG = rgb(0.96, 0.96, 0.98);

export async function renderReportPdf(report: Report): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const newPage = () => {
    page = doc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN;
  };
  const ensure = (needed: number) => {
    if (y - needed < MARGIN) newPage();
  };
  const truncate = (value: string, f: PDFFont, size: number, maxW: number): string => {
    let t = String(value ?? "");
    if (f.widthOfTextAtSize(t, size) <= maxW) return t;
    while (t.length > 1 && f.widthOfTextAtSize(`${t}…`, size) > maxW) t = t.slice(0, -1);
    return `${t}…`;
  };
  const line = (yy: number) => {
    page.drawLine({
      start: { x: MARGIN, y: yy },
      end: { x: PAGE_W - MARGIN, y: yy },
      thickness: 0.5,
      color: LINE,
    });
  };
  const write = (value: string, x: number, size: number, f: PDFFont, color = INK) => {
    page.drawText(value, { x, y, size, font: f, color });
  };

  // Title block
  write(report.title, MARGIN, 20, bold);
  y -= 22;
  write(report.subtitle, MARGIN, 11, font, MUTED);
  y -= 16;
  write(
    `Tenant: ${report.tenantName}   ·   Generated by ${report.generatedBy}`,
    MARGIN,
    9,
    font,
    MUTED,
  );
  y -= 12;
  write(`Generated ${formatReportTimestamp(report.generatedAt, "en")}`, MARGIN, 9, font, MUTED);
  y -= 18;
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_W - MARGIN, y },
    thickness: 1,
    color: LINE,
  });
  y -= 24;

  // KPIs (3 per row)
  const perRow = 3;
  const kpiW = CONTENT_W / perRow;
  for (let i = 0; i < report.kpis.length; i += perRow) {
    ensure(46);
    report.kpis.slice(i, i + perRow).forEach((kpi, col) => {
      const x = MARGIN + col * kpiW;
      page.drawText(kpi.value, { x, y, size: 18, font: bold, color: ACCENT });
      page.drawText(truncate(kpi.label.toUpperCase(), font, 8, kpiW - 8), {
        x,
        y: y - 14,
        size: 8,
        font,
        color: MUTED,
      });
    });
    y -= 46;
  }
  y -= 6;

  const drawTable = (table: ReportTable) => {
    const cols = table.columns.length;
    const colW = CONTENT_W / cols;
    const rowH = 16;
    const size = 8.5;

    const drawRow = (cells: string[], f: PDFFont, header: boolean) => {
      if (y - rowH < MARGIN) newPage();
      if (header) {
        page.drawRectangle({
          x: MARGIN,
          y: y - rowH + 4,
          width: CONTENT_W,
          height: rowH,
          color: HEADER_BG,
        });
      }
      cells.forEach((cell, i) => {
        page.drawText(truncate(String(cell ?? ""), f, size, colW - 8), {
          x: MARGIN + i * colW + 4,
          y: y - 11,
          size,
          font: f,
          color: header ? INK : BODY,
        });
      });
      line(y - rowH + 3);
      y -= rowH;
    };

    drawRow(table.columns, bold, true);
    if (table.rows.length === 0) {
      drawRow(["(none)", ...Array(cols - 1).fill("")], font, false);
    } else {
      for (const row of table.rows) drawRow(row, font, false);
    }
  };

  // Wraps a paragraph of text to `maxW`, splitting on existing newlines first — narratives like
  // "Next steps" carry a numbered list as literal `\n`-separated lines that must stay separate.
  const wrapLines = (value: string, f: PDFFont, size: number, maxW: number): string[] => {
    const out: string[] = [];
    for (const paragraph of value.split("\n")) {
      const words = paragraph.split(" ");
      let current = "";
      for (const word of words) {
        const candidate = current ? `${current} ${word}` : word;
        if (f.widthOfTextAtSize(candidate, size) > maxW && current) {
          out.push(current);
          current = word;
        } else {
          current = candidate;
        }
      }
      out.push(current);
    }
    return out;
  };

  // Sections
  for (const section of report.sections) {
    ensure(34);
    write(section.heading, MARGIN, 13, bold);
    y -= 18;
    if (section.narrative) {
      for (const narrativeLine of wrapLines(section.narrative, font, 10, CONTENT_W)) {
        ensure(14);
        write(narrativeLine, MARGIN, 10, font, MUTED);
        y -= 14;
      }
      y -= 2;
    }
    if (section.table) drawTable(section.table);
    y -= 16;
  }

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
