/**
 * Excel (.xlsx) report renderer using exceljs. A "Summary" sheet with the headline KPIs plus
 * one sheet per section table. Node-only.
 */

import ExcelJS from "exceljs";
import { formatReportTimestamp } from "./format";
import type { Report } from "./types";

const HEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FFEDEDF5" },
};

function sheetName(heading: string, index: number): string {
  const cleaned = heading
    .replace(/[\[\]:*?/\\]/g, " ")
    .trim()
    .slice(0, 28);
  return `${index + 1}. ${cleaned}`.slice(0, 31);
}

export async function renderReportXlsx(report: Report, locale: "ar" | "en" = "en"): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Rasheed";
  workbook.created = new Date(report.generatedAt);

  const summary = workbook.addWorksheet("Summary");
  summary.columns = [{ width: 32 }, { width: 26 }];
  const titleRow = summary.addRow([report.title]);
  titleRow.font = { bold: true, size: 16 };
  summary.addRow([report.subtitle]);
  summary.addRow([`Tenant: ${report.tenantName}`]);
  summary.addRow([
    `Generated by ${report.generatedBy} · ${formatReportTimestamp(report.generatedAt, locale)}`,
  ]);
  summary.addRow([]);
  const kpiHeader = summary.addRow(["KPI", "Value"]);
  kpiHeader.font = { bold: true };
  kpiHeader.eachCell((cell) => (cell.fill = HEADER_FILL));
  for (const kpi of report.kpis) summary.addRow([kpi.label, kpi.value]);

  const narrativeOnlySections = report.sections.filter((s) => !s.table && s.narrative);
  if (narrativeOnlySections.length > 0) {
    summary.addRow([]);
    const notesHeader = summary.addRow(["Notes"]);
    notesHeader.font = { bold: true, size: 12 };
    for (const section of narrativeOnlySections) {
      const headingRow = summary.addRow([section.heading]);
      headingRow.font = { bold: true };
      for (const line of (section.narrative ?? "").split("\n")) summary.addRow([line]);
      summary.addRow([]);
    }
  }

  report.sections.forEach((section, index) => {
    if (!section.table) return;
    const worksheet = workbook.addWorksheet(sheetName(section.heading, index));
    if (section.narrative) {
      for (const line of section.narrative.split("\n")) worksheet.addRow([line]);
      worksheet.addRow([]);
    }
    const header = worksheet.addRow(section.table.columns);
    header.font = { bold: true };
    header.eachCell((cell) => (cell.fill = HEADER_FILL));
    for (const row of section.table.rows) worksheet.addRow(row);
    section.table.columns.forEach((column, i) => {
      const maxCell = Math.max(
        column.length,
        ...section.table!.rows.map((r) => String(r[i] ?? "").length),
      );
      worksheet.getColumn(i + 1).width = Math.min(60, Math.max(12, maxCell + 3));
    });
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
